import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: [
        '/',
        '/globe',
        '/world-map',
        '/interactive-globe',
        '/interactive-world-map',
        '/geography',
        '/world-geography',
        '/countries',
        '/countries/*',
        '/games',
        '/news',
        '/weather',
        '/sports',
        '/business',
        '/technology',
        '/play-earth',
        '/daily',
        '/challenges',
        '/trending',
        '/explore',
        '/tournament',
        '/party',
        '/war-room',
        '/country/*',
        '/category/*',
        '/article/*',
        '/about',
        '/contact',
        '/privacy',
        '/terms',
        '/cookies',
        '/copyright',
        '/dmca',
        '/disclaimer',
        '/data-sources',
        '/accessibility',
        '/community',
        '/security',
        '/ai-transparency',
        '/advertising',
      ],
      disallow: [
        '/api/',
        '/admin/',
        '/auth/',
        '/account/',
        '/debug/',
        '/private/',
      ],
    },
    sitemap: 'https://www.mooearth.live/sitemap.xml',
  };
}

