import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'AI Transparency Policy | MooEarth.Live',
  description: 'How Artificial Intelligence is used on MooEarth.Live and our commitment to transparency.',
  alternates: {
    canonical: 'https://www.mooearth.live/ai-transparency'
  }
};

export default function AITransparency() {
  return (
    <>
      <h1 className="text-3xl md:text-4xl font-bold mb-4">AI Transparency Policy</h1>
      <p className="text-sm text-gray-400 mb-8">Last Updated: June 29, 2026</p>

      <div className="space-y-6">
        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">1. Our Commitment to Transparency</h2>
          <p>
            At MooEarth.Live, we leverage modern technology to enhance the football fan experience. This includes the use of Artificial Intelligence (AI) and Large Language Models (LLMs) to help process and summarize large amounts of sports data quickly. We believe in being fully transparent about when and how AI is used on our platform.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">2. Where AI is Used on MooEarth.Live</h2>
          <p>You may encounter AI-generated or AI-assisted content in the following areas of our site:</p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li><strong>Match Summaries:</strong> Brief text summaries explaining the outcome or key events of a football match.</li>
            <li><strong>News Aggregation:</strong> Categorizing or summarizing long-form news articles from third-party publishers into quick-read snippets.</li>
            <li><strong>Translation Assistance:</strong> Helping to translate global football news into your preferred language.</li>
            <li><strong>Chat/Search Assistants:</strong> Any interactive chatbot features designed to help you find specific fixtures or statistics.</li>
          </ul>
          <p className="mt-4">
            <em>Note: The live scoreboards, live timers, and raw statistical data (goals, cards, possession) are pulled directly from our sports data APIs and are <strong>not</strong> generated by AI.</em>
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">3. The Limitations of AI (Hallucinations)</h2>
          <p>
            While AI is powerful, it is not perfect. AI models can sometimes misunderstand context, struggle with highly nuanced sporting rules, or produce "hallucinations" (plausible-sounding but factually incorrect statements). 
          </p>
          <div className="mt-4 p-4 border-l-4 border-amber-500 bg-amber-500/10 rounded-r-lg">
            <p className="font-semibold text-amber-500 mb-2">Important Disclaimer:</p>
            <p>AI-generated summaries may contain inaccuracies regarding match events, player names, or historical context. They should <strong>never</strong> replace official announcements from FIFA, national federations, or official match referees.</p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">4. User Verification</h2>
          <p>
            We strongly encourage all users to verify important information. If an AI summary mentions a controversial red card, a record-breaking goal, or a tournament advancement scenario, please cross-reference this information with official news sources or the original publishers linked in our news feed.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">5. Continuous Improvement</h2>
          <p>
            We are constantly monitoring and refining the prompts and guardrails used by our AI systems to improve accuracy and reduce errors. If you spot an AI-generated summary that is wildly inaccurate, you can help us improve by reporting it to <a href="mailto:support@mooearth.live" className="text-emerald-400 hover:underline">support@mooearth.live</a>.
          </p>
        </section>
      </div>
    </>
  );
}
